# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#

default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: chat_space_development

test:
  <<: *default
  database: chat_space_test

production:
  <<: *default
  database: chat_space_production
  username: chat_space
  password: <%= ENV['CHAT_SPACE_DATABASE_PASSWORD'] %>
